name: barbershpo_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

#------------- PACKAGES -------------#

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  #flutter_local_notifications: ^16.3.2
  flutter_calendar_carousel: ^2.4.4
  # Utility packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.1
  flutter_otp_text_field: ^1.4.0+2


# Product Specific



#------------- ./ PACKAGES END -------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  #------------- LOCAL ASSETS -------------#:
  assets:
    #- assets/icons/
    - assets/images/photo_salon/s (1).jpg
    - assets/images/photo_salon/s (4).jpg
    - assets/images/photo_salon/s (5).jpg
    - assets/images/photo_salon/s (6).jpg
    - assets/images/photo_salon/s (7).jpg
    - assets/images/img2.jpg
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/animations/


  #------------- LOCAL FONTS -------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

